name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensures all branches are fetched

      - name: Generate Pac-Man Contribution Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Debug - Check if Graph Exists
        run: ls -R dist # Check inside the 'dist' folder

      - name: Commit and Push Updated Graph
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git checkout -B output
          
          mv dist/pacman-contribution-graph.svg . || echo "File not found!"
          mv dist/pacman-contribution-graph-dark.svg . || echo "File not found!"
          
          git add pacman-contribution-graph.svg pacman-contribution-graph-dark.svg || echo "Nothing to add"
          git commit -m "Updated Pac-Man contribution graph" || echo "No changes to commit"

          git push origin output --force
