name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensures all branches are fetched

      - name: Generate Pac-Man Contribution Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Commit and Push Updated Graph
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Ensure we're on the correct branch
          git checkout -B output
          
          # Add and commit the changes
          git add pacman-contribution-graph.svg pacman-contribution-graph-dark.svg
          git commit -m "Updated Pac-Man contribution graph" || echo "No changes to commit"

          # Push with authentication
          git push origin output --force
